"""Repository analyzer for PR changed file processing.

Fetches changed files from a pull request, detects languages,
filters out binary/generated files, and prepares file data
for agent analysis.
"""

from __future__ import annotations

import json
import logging
import time
from typing import Optional

from core.github_client import GitHubClient
from models.schemas import ChangedFile

logger = logging.getLogger("codesage")

SUPPORTED_LANGUAGES = {"python", "javascript", "typescript"}

LANGUAGE_MAP: dict[str, str] = {
    ".py": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".go": "go",
    ".java": "java",
    ".rb": "ruby",
    ".rs": "rust",
    ".cpp": "cpp",
    ".c": "c",
    ".cs": "csharp",
    ".php": "php",
    ".swift": "swift",
    ".kt": "kotlin",
}

GENERATED_FILE_PATTERNS = [
    "_pb2.py",
    "_pb2_grpc.py",
    ".min.js",
    ".min.css",
    ".generated.",
    ".g.dart",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Pipfile.lock",
    "poetry.lock",
    "go.sum",
    "Cargo.lock",
]

GENERATED_CONTENT_MARKERS = [
    "generated",
    "auto-generated",
    "do not edit",
    "this file is generated",
    "code generated by",
]

BINARY_EXTENSIONS = {
    ".png", ".jpg", ".jpeg", ".gif", ".ico", ".svg",
    ".woff", ".woff2", ".ttf", ".eot",
    ".zip", ".tar", ".gz", ".bz2",
    ".exe", ".dll", ".so", ".dylib",
    ".pdf", ".doc", ".docx",
    ".pyc", ".pyo", ".class",
}

MAX_FILE_SIZE = 500_000


class RepoAnalyzer:
    """Analyzes PR changed files and prepares them for agent review.

    Attributes:
        github_client: GitHubClient instance for API calls.
    """

    def __init__(self, github_client: GitHubClient) -> None:
        """Initialize the repo analyzer.

        Args:
            github_client: Authenticated GitHubClient instance.
        """
        self.github_client = github_client

    async def analyze_pr(
        self,
        repo: str,
        pr_number: int,
        head_sha: str,
        base_sha: str,
    ) -> list[ChangedFile]:
        """Fetch and process all changed files in a pull request.

        Fetches the file list, populates content, detects languages,
        and filters out unsupported/binary/generated files.

        Args:
            repo: Repository in owner/repo format.
            pr_number: Pull request number.
            head_sha: SHA of the PR head commit.
            base_sha: SHA of the PR base commit.

        Returns:
            List of ChangedFile objects ready for agent analysis.
            Only includes supported languages with content populated.
        """
        start = time.time()

        raw_files = await self.github_client.get_pr_files(
            repo, pr_number, head_sha
        )

        processed: list[ChangedFile] = []
        skipped_reasons: dict[str, int] = {}

        for f in raw_files:
            skip_reason = self._should_skip(f)
            if skip_reason:
                skipped_reasons[skip_reason] = (
                    skipped_reasons.get(skip_reason, 0) + 1
                )
                continue

            if not f.language:
                f.language = self.detect_language(f.filename)

            if f.language not in SUPPORTED_LANGUAGES:
                skipped_reasons["unsupported_language"] = (
                    skipped_reasons.get("unsupported_language", 0) + 1
                )
                continue

            if f.content and self.is_generated_file(f.filename, f.content):
                skipped_reasons["generated"] = (
                    skipped_reasons.get("generated", 0) + 1
                )
                continue

            processed.append(f)

        elapsed = time.time() - start
        logger.info(
            json.dumps({
                "timestamp": time.time(),
                "level": "INFO",
                "agent": "RepoAnalyzer",
                "job_id": "",
                "message": "PR analysis complete",
                "repo": repo,
                "pr": pr_number,
                "total_files": len(raw_files),
                "processed_files": len(processed),
                "skipped": skipped_reasons,
                "elapsed_s": round(elapsed, 2),
            })
        )
        return processed

    def _should_skip(self, file: ChangedFile) -> Optional[str]:
        """Determine if a file should be skipped from analysis.

        Args:
            file: ChangedFile to evaluate.

        Returns:
            Reason string if the file should be skipped, None otherwise.
        """
        if file.status == "removed":
            return "removed"

        ext = self._get_extension(file.filename)
        if ext in BINARY_EXTENSIONS:
            return "binary"

        if not file.content:
            return "no_content"

        if len(file.content) > MAX_FILE_SIZE:
            return "too_large"

        return None

    @staticmethod
    def detect_language(filename: str) -> Optional[str]:
        """Detect programming language from file extension.

        Args:
            filename: File path or name.

        Returns:
            Language identifier string, or None if unrecognized.
        """
        dot_idx = filename.rfind(".")
        if dot_idx == -1:
            return None
        ext = filename[dot_idx:].lower()
        return LANGUAGE_MAP.get(ext)

    @staticmethod
    def is_generated_file(filename: str, content: str) -> bool:
        """Check if a file is auto-generated and should be skipped.

        Args:
            filename: File path or name.
            content: File content string.

        Returns:
            True if the file appears to be generated.
        """
        lower_name = filename.lower()
        for pattern in GENERATED_FILE_PATTERNS:
            if pattern in lower_name:
                return True

        first_lines = content[:500].lower()
        for marker in GENERATED_CONTENT_MARKERS:
            if marker in first_lines:
                return True

        return False

    @staticmethod
    def _get_extension(filename: str) -> str:
        """Extract the file extension including the dot.

        Args:
            filename: File path or name.

        Returns:
            Extension string like '.py', or empty string.
        """
        dot_idx = filename.rfind(".")
        if dot_idx == -1:
            return ""
        return filename[dot_idx:].lower()
